# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44f7a4c761b3156677b5e8fb7699929121f37ca8bc962fb5dc75deb21c1407bd19206563c441af3aa34d18515a3ddfb87c61eb5e46a2b92cbb54d4731bd7226e

test:
  secret_key_base: 11fc2b50b1346f75747789238807eeaba1b9d7d338ca9c3b544b974f333749f4fe2143e8e4b2423a0e551859b3b9ca75b024570fad918795fb3b8e9b7b0c4db9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
